apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: object-detection-model-weights
  namespace: partha
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi